### ISSUE TITLE
Final File

### ISSUE THREAD

**Issue by taniabarreira** [brightcove/videojs-dock#12]
Hello, can we have access to the final file: videojs-dock.min.js
Thank You

**Comment by misteroneill** [comment]
Hi @taniabarreira,

You can get that file today in a few ways. It'll be available if you install this plugin via npm (i.e. `npm install videojs-dock`) or you can download it [from GitHub's list of releases](https://github.com/brightcove/videojs-dock/releases) or you can use [the unpkg CDN](https://unpkg.com/videojs-dock@2.0.3/dist/videojs-dock.min.js).

Hope this helps!

**Comment by taniabarreira** [comment]
Thank's misteroneill
