### ISSUE TITLE
Integrating the videojs-dock plugin with the videojs-playlist plugin.

### ISSUE THREAD

**Issue by zaynzafar** [brightcove/videojs-dock#19]
Hi,

I am wondering how I can integrate this dock plugin with the playlist plugin. I have set the name and description of the videos in the playlist array but how can I get it to appear on the dock when you switch videos or go to the next / prev item in the playlist?

Brightcove have done it on their player here:
[https://support.brightcove.com/playlist-ui-plugin](https://support.brightcove.com/playlist-ui-plugin)

Thanks

**Comment by BrandonOCasey** [comment]
OK so the playlist plugin should fire an event called `playlistitem` when the playlist item changes. Using that you should be able to update the dock. I have not tested this code, but I think this should work:

```js
player.on('playlistitem', function(event, video) {
  player.dock().title.update(video.title, video.description);	
});
```

**Comment by zaynzafar** [comment]
@BrandonOCasey I am getting the following error:

`video.min.js:12 VIDEOJS: ERROR: TypeError: Cannot read property 'title' of undefined
    at h.<anonymous> (scripts.js:222)
    at HTMLDivElement.r (video.min.js:12)
    at HTMLDivElement.o.dispatcher.o.dispatcher (video.min.js:12)
    at Tt (video.min.js:12)
    at h.trigger (video.min.js:12)
    at h.<anonymous> (videojs-playlist.min.js:33)
    at r (video.min.js:12)`

This is my code structure for the playlist / dock:

```
  player.playlist([{
      name: 'Video 1',
      description: 'Video 1',
      sources: [{
        src: 'http://view.vzaar.com/14749665/video',
        type: 'video/mp4'
      }]
    },
    {
      name: 'Video 2',
      description: 'Video 2',
      sources: [{
        src: 'http://view.vzaar.com/13078537/video',
        type: 'video/mp4'
      }]
    }
  ]);

  player.dock({
  // unsure what to populate this with since the name/description is in the player.playlist method?
  });

  player.on('playlistitem', function(event, video) {
    player.dock().title.update(video.title, video.description);	
  });
 
```

**Comment by gkatsev** [comment]
You can actually re-initialize the dock multiple times without bad effects

so you can do 
```js
player.on('playlistitem', function(event, video) {
  player.dock({
    title: video.title,
    description: video.description    
  })
});
```

Then, you could just not initialize the dock initially or just initialize it to with empty strings.

**Comment by gkatsev** [comment]
Also, docs for `playlistitem` event: https://github.com/brightcove/videojs-playlist/blob/master/docs/api.md#playlistitem

Looks like we're lacking in docs for the repo.

**Comment by zaynzafar** [comment]
@gkatsev This was useful and solved my problem :)

Thanks a lot ...

**Comment by gkatsev** [comment]
You're welcome.

**Comment by zaynzafar** [comment]
@gkatsev Hi Gary, I'm trying to do the same thing with the videojs overlays (each video has it's own set of overlays), but it's not working since it's in an array:

```
player.on('playlistitem', function (event, video) {
    player.overlay({
      overlays: [{
        content: video.content,
        showBackground: video.showBackground,
        start: video.start,
        end: video.end,
        align: video.align,
        class: video.class
      }]
    });

What am i doing wrong here? Please help shed some light ! thanks
  });
```

**Comment by gkatsev** [comment]
Answering here https://github.com/brightcove/videojs-overlay/issues/64
