### ISSUE TITLE
Displaying dock text issues.

### ISSUE THREAD

**Issue by greenpdx** [brightcove/videojs-dock#54]
I have included videojs-dock and I see it in the "activePlugins" field of the player. As the player is loading, I see the text I added as an option, but then it is gone. At first the height was 0 (using the debugger) I then added some css to give it height, but I still can not see it.

I am using vue as the front end . 

My question is not how to fix it but how to debug it. ( fixing it is OK also)
What are the classes that should be with it?

Because I never had it working I do not know what it is  

### Expected
Please describe what you expected to see.
I expected to see the text

### Actual
Please describe what actually happened.
see video but no text

### Error output
If there are any errors at all, please include them here.
none

#### videojs
what version of videojs does this occur with?
```
    "axios": "^0.18.0",
    "opencv.js": "^1.2.1",
    "video.js": "^7.4.1",
    "videojs-dock": "^2.1.4",
    "videojs-hotkeys": "^0.2.25",
    "videojs-overlay": "^2.1.4",
    "videojs-playlist": "^4.2.6",
    "vue": "^2.6.6",
    "vue-video-player": "^5.0.2",
    "vuetify": "^1.5.6"
```

#### browsers
chrome

#### OSes
Linux

### plugins
see above

```
// player
        const self = this
        this.player = videojs(this.$refs.video, videoOptions, function() {

          // events
          const events = DEFAULT_EVENTS.concat(self.events).concat(self.globalEvents)

          // watch events
          const onEdEvents = {}
          for (let i = 0; i < events.length; i++) {
            if (typeof events[i] === 'string' && onEdEvents[events[i]] === undefined) {
              (event => {
                onEdEvents[event] = null
                this.on(event, () => {
                  emitPlayerState(event, true)
                })
              })(events[i])
            }
          }

          // watch timeupdate
          this.on('timeupdate', function() {
            emitPlayerState('timeupdate', this.currentTime())
          })

          // player readied
          self.$emit('ready', this)
        })
      },
```
partial options ( typed in by hand so ignore syntax)
```
plugins: {
   dock: {
      desc: 'Not Again',
      title: 'Dont Worry'
   },
   hotkeys: {},
   playlist: {}
},
fill: true,
controls: true,
controlBar: {
   ....... More stuff
},
sources: [],
techOrder: ['html5']
userActions: {
   doubleClick:  function......
   hotkeys: function.....
}
```

**Comment by gkatsev** [comment]
Looks like this issue got lost in the grind.
It seems like it's an issue of timing and ordering when it's initialized as part of the `plugins` option in the player options. It looks like it gets created and put into the player element before the poster is created which ends up hiding the text.
If it's initialized manually after the fact via `player.dock()`, it seems to work fine.

I've made a fix.
