### ISSUE TITLE
Dock prevents ad clickthroughs in IE10 and below

### ISSUE THREAD

**Issue by incompl** [brightcove/videojs-dock#9]
A workaround might be to remove or resize the dock element completely when it's not shown.

**Comment by draja91** [comment]
https://docs.google.com/a/brightcove.com/spreadsheets/d/1h7zbyNMBThzPBZWq0kjihIrZnHqg4uFztvblPnva9jk/edit?usp=sharing

**Comment by incompl** [comment]
Awww, you're not gonna make it work in IE10? 😉

**Comment by gkatsev** [comment]
We're finally dropping support for IE11, what is this IE10 you're speaking off?

**Comment by misteroneill** [comment]
Hahaha @incompl - PRs accepted! 😉
